// packages/ui/vue-ui/src/WalletDisconnectButton.vue
<script setup lang="ts">
import { toRefs, computed } from 'vue';
import { useWallet } from '@solana/wallet-adapter-vue';
import WalletButton from './WalletButton.vue';
import WalletIcon from './WalletIcon.vue';

const emit = defineEmits(['click'])
const props = defineProps({ disabled: Boolean });
const { disabled } = toRefs(props);

const { wallet, disconnect, disconnecting } = useWallet();

const handleClick = event => {
    emit('click', event);
    if (event.defaultPrevented) return;
    disconnect().catch(() => {});
};

const content = computed(() => {
    if (disconnecting.value) return 'Disconnecting ...';
    if (wallet.value) return 'Disconnect';
    return 'Disconnect Wallet';
});
</script>

<template>
    <wallet-button
        class="wallet-adapter-button-trigger"
        :disabled="disabled || ! wallet"
        @click="handleClick"
    >
        <template #start-icon v-if="wallet">
            <wallet-icon :wallet="wallet"></wallet-icon>
        </template>
        <slot>
            {{ content }}
        </slot>
    </wallet-button>
</template>

// packages/phantom-ui/src/WalletDisconnectButton.tsx
import { useWallet } from '@solana/wallet-adapter-react';
import React, { FC, MouseEventHandler, useCallback, useMemo } from 'react';
import { Button, ButtonProps } from './Button';
import { WalletIcon } from './WalletIcon';

export const WalletDisconnectButton: FC<ButtonProps> = ({ color, children, disabled, onClick, ...props }) => {
    const { wallet, disconnect, disconnecting } = useWallet();

    const handleClick: MouseEventHandler<HTMLButtonElement> = useCallback(
        (event) => {
            if (onClick) onClick(event);
            // eslint-disable-next-line @typescript-eslint/no-empty-function
            if (!event.defaultPrevented) disconnect().catch(() => {});
        },
        [onClick, disconnect]
    );

    const content = useMemo(() => {
        if (children) return children;
        if (disconnecting) return 'Disconnecting ...';
        if (wallet) return 'Disconnect';
        return 'Disconnect Wallet';
    }, [children, disconnecting, wallet]);

    return (
        <Button
            color={color}
            onClick={handleClick}
            disabled={disabled || !wallet}
            icon={<WalletIcon wallet={wallet} />}
            style={{}}
        >
            {content}
        </Button>
    );
};
