// packages/ui/react-ui/src/WalletMultiButton.tsx
import { useWallet } from '@solana/wallet-adapter-react';
import React, { FC, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Button, ButtonProps } from './Button';
import { useWalletModal } from './useWalletModal';
import { WalletConnectButton } from './WalletConnectButton';
import { WalletIcon } from './WalletIcon';
import { WalletModalButton } from './WalletModalButton';

export const WalletMultiButton: FC<ButtonProps> = ({ children, ...props }) => {
    const { publicKey, wallet, disconnect } = useWallet();
    const { setVisible } = useWalletModal();
    const [copied, setCopied] = useState(false);
    const [active, setActive] = useState(false);
    const ref = useRef<HTMLUListElement>(null);

    const base58 = useMemo(() => publicKey?.toBase58(), [publicKey]);
    const content = useMemo(() => {
        if (children) return children;
        if (!wallet || !base58) return null;
        return base58.slice(0, 4) + '..' + base58.slice(-4);
    }, [children, wallet, base58]);

    const copyAddress = useCallback(async () => {
        if (base58) {
            await navigator.clipboard.writeText(base58);
            setCopied(true);
            setTimeout(() => setCopied(false), 400);
        }
    }, [base58]);

    const openDropdown = useCallback(() => setActive(true), [setActive]);

    const closeDropdown = useCallback(() => setActive(false), [setActive]);

    const openModal = useCallback(() => {
        setVisible(true);
        closeDropdown();
    }, [setVisible, closeDropdown]);

    useEffect(() => {
        const listener = (event: MouseEvent | TouchEvent) => {
            const node = ref.current;

            // Do nothing if clicking dropdown or its descendants
            if (!node || node.contains(event.target as Node)) return;

            closeDropdown();
        };

        document.addEventListener('mousedown', listener);
        document.addEventListener('touchstart', listener);

        return () => {
            document.removeEventListener('mousedown', listener);
            document.removeEventListener('touchstart', listener);
        };
    }, [ref, closeDropdown]);

    if (!wallet) return <WalletModalButton {...props}>{children}</WalletModalButton>;
    if (!base58) return <WalletConnectButton {...props}>{children}</WalletConnectButton>;

    return (
        <div className="wallet-adapter-dropdown">
            <Button
                aria-expanded={active}
                className="wallet-adapter-button-trigger"
                style={{ pointerEvents: active ? 'none' : 'auto', ...props.style }}
                onClick={openDropdown}
                startIcon={<WalletIcon wallet={wallet} />}
                {...props}
            >
                {content}
            </Button>
            <ul
                aria-label="dropdown-list"
                className={`wallet-adapter-dropdown-list ${active && 'wallet-adapter-dropdown-list-active'}`}
                ref={ref}
                role="menu"
            >
                <li onClick={copyAddress} className="wallet-adapter-dropdown-list-item" role="menuitem">
                    {copied ? 'Copied' : 'Copy address'}
                </li>
                <li onClick={openModal} className="wallet-adapter-dropdown-list-item" role="menuitem">
                    Connect a different wallet
                </li>
                <li onClick={disconnect} className="wallet-adapter-dropdown-list-item" role="menuitem">
                    Disconnect
                </li>
            </ul>
        </div>
    );
};

// packages/ui/vue-ui/src/WalletMultiButton.vue
<script setup>
import { ref, computed, watchEffect } from 'vue'
import { useWallet } from '@solana/wallet-adapter-vue';
import { useWalletModal } from './useWalletModal';
import WalletConnectButton from './WalletConnectButton';
import WalletModalButton from './WalletModalButton';
import WalletButton from './WalletButton';
import WalletIcon from './WalletIcon';

const { publicKey, wallet, disconnect } = useWallet();
const { showModal } = useWalletModal();
const copied = ref(false);
const active = ref(false);
const dropdown = ref(null);

const base58 = computed(() => publicKey.value?.toBase58());
const content = computed(() => {
    if (! wallet.value || ! base58.value) return null;
    return base58.value.slice(0, 4) + '..' + base58.value.slice(-4);
});

const copyAddress = async () => {
    if (! base58.value) return;
    await navigator.clipboard.writeText(base58.value);
    copied.value = true;
    setTimeout(() => copied.value = false, 400);
};

const openDropdown = () => active.value = true;
const closeDropdown = () => active.value = false;
const openModal = () => {
    showModal();
    closeDropdown();
};

watchEffect(onInvalidate => {
    const listener = event => {
        const node = dropdown.value;
        // Do nothing if clicking dropdown or its descendants
        if (!node || node.contains(event.target)) return;
        closeDropdown();
    };
    document.addEventListener('mousedown', listener);
    document.addEventListener('touchstart', listener);
    onInvalidate(() => {
        document.removeEventListener('mousedown', listener);
        document.removeEventListener('touchstart', listener);
    });
});
</script>

<template>
    <wallet-modal-button v-if="! wallet">
        <slot></slot>
    </wallet-modal-button>
    <wallet-connect-button v-else-if="! base58">
        <slot></slot>
    </wallet-connect-button>
    <div v-else className="wallet-adapter-dropdown">
        <wallet-button
            class="wallet-adapter-button-trigger"
            :style="{ pointerEvents: active ? 'none' : 'auto' }"
            :aria-expanded="active"
            @click="openDropdown"
        >
            <template #start-icon>
                <wallet-icon :wallet="wallet"></wallet-icon>
            </template>
            <slot>{{ content }}</slot>
        </wallet-button>
        <ul
            aria-label="dropdown-list"
            class="wallet-adapter-dropdown-list"
            :class="{ 'wallet-adapter-dropdown-list-active': active }"
            ref="dropdown"
            role="menu"
        >
            <li @click="copyAddress" class="wallet-adapter-dropdown-list-item" role="menuitem">
                {{ copied ? 'Copied' : 'Copy address' }}
            </li>
            <li @click="openModal" class="wallet-adapter-dropdown-list-item" role="menuitem">
                Connect a different wallet
            </li>
            <li @click="disconnect" class="wallet-adapter-dropdown-list-item" role="menuitem">
                Disconnect
            </li>
        </ul>
    </div>
</template>
