// packages/ui/react-ui/src/WalletModal.tsx
import { useWallet } from '@solana/wallet-adapter-react';
import { WalletName } from '@solana/wallet-adapter-base';
import React, { FC, MouseEvent, useCallback, useLayoutEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { Button } from './Button';
import { Collapse } from './Collapse';
import { useWalletModal } from './useWalletModal';
import { WalletListItem } from './WalletListItem';

export interface WalletModalProps {
    className?: string;
    featuredWallets?: number;
    container?: string;
}

export const WalletModal: FC<WalletModalProps> = ({ className = '', featuredWallets = 3, container = 'body' }) => {
    const ref = useRef<HTMLDivElement>(null);
    const { wallets, select } = useWallet();
    const { setVisible } = useWalletModal();
    const [expanded, setExpanded] = useState(false);
    const [fadeIn, setFadeIn] = useState(false);
    const [portal, setPortal] = useState<Element | null>(null);

    const [featured, more] = useMemo(
        () => [wallets.slice(0, featuredWallets), wallets.slice(featuredWallets)],
        [wallets, featuredWallets]
    );

    const hideModal = useCallback(() => {
        setFadeIn(false);
        setTimeout(() => setVisible(false), 150);
    }, [setFadeIn, setVisible]);

    const handleClose = useCallback(
        (event: MouseEvent) => {
            event.preventDefault();
            hideModal();
        },
        [hideModal]
    );

    const handleWalletClick = useCallback(
        (event: MouseEvent, walletName: WalletName) => {
            select(walletName);
            handleClose(event);
        },
        [select, handleClose]
    );

    const handleCollapseClick = useCallback(() => setExpanded(!expanded), [setExpanded, expanded]);

    const handleTabKey = useCallback(
        (event: KeyboardEvent) => {
            const node = ref.current;
            if (!node) return;

            // here we query all focusable elements
            const focusableElements = node.querySelectorAll('button');
            const firstElement = focusableElements[0];
            const lastElement = focusableElements[focusableElements.length - 1];

            if (event.shiftKey) {
                // if going backward by pressing tab and firstElement is active, shift focus to last focusable element
                if (document.activeElement === firstElement) {
                    lastElement.focus();
                    event.preventDefault();
                }
            } else {
                // if going forward by pressing tab and lastElement is active, shift focus to first focusable element
                if (document.activeElement === lastElement) {
                    firstElement.focus();
                    event.preventDefault();
                }
            }
        },
        [ref]
    );

    useLayoutEffect(() => {
        const handleKeyDown = (event: KeyboardEvent) => {
            if (event.key === 'Escape') {
                hideModal();
            } else if (event.key === 'Tab') {
                handleTabKey(event);
            }
        };

        // Get original overflow
        const { overflow } = window.getComputedStyle(document.body);
        // Hack to enable fade in animation after mount
        setTimeout(() => setFadeIn(true), 0);
        // Prevent scrolling on mount
        document.body.style.overflow = 'hidden';
        // Listen for keydown events
        window.addEventListener('keydown', handleKeyDown, false);

        return () => {
            // Re-enable scrolling when component unmounts
            document.body.style.overflow = overflow;
            window.removeEventListener('keydown', handleKeyDown, false);
        };
    }, [hideModal, handleTabKey]);

    useLayoutEffect(() => setPortal(document.querySelector(container)), [setPortal, container]);

    return (
        portal &&
        createPortal(
            <div
                aria-labelledby="wallet-adapter-modal-title"
                aria-modal="true"
                className={`wallet-adapter-modal ${fadeIn && 'wallet-adapter-modal-fade-in'} ${className}`}
                ref={ref}
                role="dialog"
            >
                <div className="wallet-adapter-modal-container">
                    <div className="wallet-adapter-modal-wrapper">
                        <button onClick={handleClose} className="wallet-adapter-modal-button-close">
                            <svg width="14" height="14">
                                <path d="M14 12.461 8.3 6.772l5.234-5.233L12.006 0 6.772 5.234 1.54 0 0 1.539l5.234 5.233L0 12.006l1.539 1.528L6.772 8.3l5.69 5.7L14 12.461z" />
                            </svg>
                        </button>
                        <h1 className="wallet-adapter-modal-title">Connect a wallet on Solana to continue</h1>
                        <ul className="wallet-adapter-modal-list">
                            {featured.map((wallet) => (
                                <WalletListItem
                                    key={wallet.name}
                                    handleClick={(event) => handleWalletClick(event, wallet.name)}
                                    wallet={wallet}
                                />
                            ))}
                            {more.length && (
                                <Collapse expanded={expanded} id="wallet-adapter-modal-collapse">
                                    {more.map((wallet) => (
                                        <WalletListItem
                                            key={wallet.name}
                                            handleClick={(event) => handleWalletClick(event, wallet.name)}
                                            tabIndex={expanded ? 0 : -1}
                                            wallet={wallet}
                                        />
                                    ))}
                                </Collapse>
                            )}
                        </ul>
                        {more.length && (
                            <button
                                className="wallet-adapter-modal-list-more"
                                onClick={handleCollapseClick}
                                tabIndex={0}
                            >
                                <span>{expanded ? 'Less ' : 'More '}options</span>
                                <svg
                                    width="13"
                                    height="7"
                                    viewBox="0 0 13 7"
                                    xmlns="http://www.w3.org/2000/svg"
                                    className={`${expanded ? 'wallet-adapter-modal-list-more-icon-rotate' : ''}`}
                                >
                                    <path
                                        d="M0.71418 1.626L5.83323 6.26188C5.91574 6.33657 6.0181 6.39652 6.13327 6.43762C6.24844 6.47872 6.37371 6.5 6.50048 6.5C6.62725 6.5 6.75252 6.47872 6.8677 6.43762C6.98287 6.39652 7.08523 6.33657 7.16774 6.26188L12.2868 1.626C12.7753 1.1835 12.3703 0.5 11.6195 0.5H1.37997C0.629216 0.5 0.224175 1.1835 0.71418 1.626Z"
                                        fill="#D6A4FF"
                                    />
                                </svg>
                            </button>
                        )}
                        <div className="wallet-adapter-modal-bottom">
                            <h1 className="wallet-adapter-modal-bottom-title">Need a wallet on Solana?</h1>
                            <p className="wallet-adapter-modal-bottom-info">
                                To begin, you'll need to create wallet and add some funds.
                            </p>
                            <button
                                type="button"
                                className="wallet-adapter-modal-bottom-button"
                                onClick={(event) => handleWalletClick(event, 'Torus' as WalletName)}
                            >
                                Get started
                            </button>
                        </div>
                    </div>
                </div>
                <div className="wallet-adapter-modal-overlay" onMouseDown={handleClose} />
            </div>,
            portal
        )
    );
};

// packages/ui/vue-ui/src/WalletModal.vue
<script lang="ts">
import { computed, ref, watchPostEffect, defineComponent } from 'vue';
import { WalletName } from '@solana/wallet-adapter-wallets';
import { useWallet } from '@solana/wallet-adapter-vue';
import { useWalletModal } from './useWalletModal';
import WalletButton from './WalletButton.vue';
import WalletListItem from './WalletListItem.vue';

export default defineComponent({
    name: 'wallet-modal',
    components: {
        WalletButton,
        WalletListItem,
    },
    props: {
        featuredWallets: { type: Number, default: 3 },
        container: { type: String, default: 'body' },
        logo: String,
    },
    setup ({ featuredWallets: featuredWalletsNumber, container, logo }) {
        const { wallets, select } = useWallet();
        const { visible, hideModal } = useWalletModal();
        const modal = ref<Element>();
        const expanded = ref(false);
        const featuredWallets = computed(() => wallets.slice(0, featuredWalletsNumber));
        const otherWallets = computed(() => wallets.slice(featuredWalletsNumber));

        const selectWallet = (walletName: WalletName) => {
            select(walletName);
            hideModal();
        };

        const handleTabKey = (event: KeyboardEvent) => {
            const node = modal.value;
            if (!node) return;

            // here we query all focusable elements
            const focusableElements = node.querySelectorAll('button');
            const firstElement = focusableElements[0];
            const lastElement = focusableElements[focusableElements.length - 1];

            if (event.shiftKey) {
                // if going backward by pressing tab and firstElement is active, shift focus to last focusable element
                if (document.activeElement === firstElement) {
                    lastElement.focus();
                    event.preventDefault();
                }
            } else {
                // if going forward by pressing tab and lastElement is active, shift focus to first focusable element
                if (document.activeElement === lastElement) {
                    firstElement.focus();
                    event.preventDefault();
                }
            }
        };

        watchPostEffect(onInvalidate => {
            const handleKeyDown = (event: KeyboardEvent) => {
                if (event.key === 'Escape') {
                    hideModal();
                } else if (event.key === 'Tab') {
                    handleTabKey(event);
                }
            };

            // Get original overflow
            const { overflow } = window.getComputedStyle(document.body);
            // Prevent scrolling on mount
            document.body.style.overflow = 'hidden';
            // Listen for keydown events
            window.addEventListener('keydown', handleKeyDown, false);

            onInvalidate(() => {
                // Re-enable scrolling when component unmounts
                document.body.style.overflow = overflow;
                window.removeEventListener('keydown', handleKeyDown, false);
            });
        });

        return {
            container,
            logo,
            visible,
            expanded,
            featuredWallets,
            otherWallets,
            modal,
            selectWallet,
            hideModal,
        }
    },
});
</script>

<template>
    <teleport :to="container" v-if="visible">
        <div
            aria-labelledby="wallet-adapter-modal-title"
            aria-modal="true"
            class="wallet-adapter-modal wallet-adapter-modal-fade-in"
            ref="modal"
            role="dialog"
        >
            <div class="wallet-adapter-modal-container">
                <div class="wallet-adapter-modal-wrapper" :class="{ 'wallet-adapter-modal-wrapper-no-logo': ! $slots.logo }">
                    <div class="wallet-adapter-modal-logo-wrapper" v-if="$slots.logo">
                        <slot name="logo">
                            <img alt="logo" class="wallet-adapter-modal-logo" :src="logo" />
                        </slot>
                    </div>
                    <h1 class="wallet-adapter-modal-title" id="wallet-adapter-modal-title">
                        Connect Wallet
                    </h1>
                    <button @click.prevent="hideModal" class="wallet-adapter-modal-button-close">
                        <svg width="14" height="14">
                            <path d="M14 12.461 8.3 6.772l5.234-5.233L12.006 0 6.772 5.234 1.54 0 0 1.539l5.234 5.233L0 12.006l1.539 1.528L6.772 8.3l5.69 5.7L14 12.461z" />
                        </svg>
                    </button>
                    <ul class="wallet-adapter-modal-list">
                        <wallet-list-item
                            v-for="wallet in featuredWallets"
                            :key="wallet.name"
                            :wallet="wallet"
                            @click="selectWallet(wallet.name)"
                        ></wallet-list-item>
                    </ul>
                    <template v-if="otherWallets.length > 0">
                        <ul class="wallet-adapter-modal-list" v-if="expanded">
                            <wallet-list-item
                                v-for="wallet in otherWallets"
                                :key="wallet.name"
                                :wallet="wallet"
                                @click="selectWallet(wallet.name)"
                            ></wallet-list-item>
                        </ul>
                        <wallet-button
                            aria-controls="wallet-adapter-modal-collapse"
                            :aria-expanded="expanded"
                            class="wallet-adapter-modal-collapse-button"
                            :class="{ 'wallet-adapter-modal-collapse-button-active': expanded }"
                            @click="expanded = ! expanded"
                        >
                            {{ expanded ? 'Less' : 'More' }} options
                            <template #end-icon>
                                <svg width="11" height="6" xmlns="http://www.w3.org/2000/svg">
                                    <path d="m5.938 5.73 4.28-4.126a.915.915 0 0 0 0-1.322 1 1 0 0 0-1.371 0L5.253 3.736 1.659.272a1 1 0 0 0-1.371 0A.93.93 0 0 0 0 .932c0 .246.1.48.288.662l4.28 4.125a.99.99 0 0 0 1.37.01z" />
                                </svg>
                            </template>
                        </wallet-button>
                    </template>
                </div>
            </div>
            <div class="wallet-adapter-modal-overlay" @mousedown="hideModal" />
        </div>
    </teleport>
</template>
