// packages/ui/svelte-ui/src/lib/WalletConnectButton.svelte
<script lang="ts">
	import { walletStore } from '@solana/wallet-adapter-svelte';
	import WalletButton from './WalletButton.svelte';

	export let disabled: boolean = false;

	let content;

	$: ({ wallet, connect, connecting, connected } = $walletStore);

	$: {
		content = 'Connect Wallet';
		if (wallet) content = 'Connect';
		if (connecting) content = 'Connecting ...';
		if (connected) content = 'Connected';
	}

	function handleClick(e: MouseEvent) {
		connect().catch(() => {});
	}
</script>

<WalletButton
	on:click={handleClick}
	disabled={disabled || !wallet || connecting || connected}
	class="wallet-adapter-button-trigger"
>
	<svelte:fragment slot="start-icon">
		{#if wallet}
			<img src={wallet.icon} alt={`${wallet.name} icon`} />
		{/if}
	</svelte:fragment>
	{content}
</WalletButton>

// packages/ui/vue-ui/src/WalletConnectButton.vue
<script lang="ts">
import { computed, defineComponent } from 'vue';
import { useWallet } from '@solana/wallet-adapter-vue';
import WalletButton from './WalletButton.vue';
import WalletIcon from './WalletIcon.vue';

export default defineComponent({
    name: 'wallet-connect-button',
    components: {
        WalletButton,
        WalletIcon,
    },
    props: {
        disabled: Boolean,
    },
    setup ({ disabled }, { emit }) {
        const { wallet, connect, connecting, connected } = useWallet();

        const content = computed(() => {
            if (connecting.value) return 'Connecting ...';
            if (connected.value) return 'Connected';
            if (wallet.value) return 'Connect';
            return 'Connect Wallet';
        });

        const handleClick = (event: MouseEvent) => {
            emit('click', event);
            if (event.defaultPrevented) return;
            connect().catch(() => {});
        };

        return {
            wallet,
            disabled,
            connecting,
            connected,
            content,
            handleClick,
        };
    },
});
</script>

<template>
    <wallet-button
        class="wallet-adapter-button-trigger"
        :disabled="disabled || ! wallet || connecting || connected"
        @click="handleClick"
    >
        <template #start-icon v-if="wallet">
            <wallet-icon :wallet="wallet"></wallet-icon>
        </template>
        <slot>
            {{ content }}
        </slot>
    </wallet-button>
</template>
