// packages/ui/vue-ui/src/WalletButton.vue
<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
    name: 'wallet-button',
    setup (props, { slots }) {
        const justifyContent = (slots['end-icon'] || slots['start-icon']) ? 'space-between' : 'center';

        return { justifyContent };
    },
});
</script>

<template>
    <button class="wallet-adapter-button" :style="`justify-content: ${justifyContent};`">
        <i v-if="$slots['start-icon']" className="wallet-adapter-button-start-icon">
            <slot name="start-icon"></slot>
        </i>
        <slot></slot>
        <i v-if="$slots['end-icon']" className="wallet-adapter-button-end-icon">
            <slot name="end-icon"></slot>
        </i>
    </button>
</template>

// packages/ui/svelte-ui/src/WalletButton.svelte
<script lang="ts">
	export let disabled: boolean = false;

	let className: string = '';
	export { className as class };

	let justifyContent: string =
		$$slots['end-icon'] || $$slots['start-icon'] ? 'space-between' : 'center';
</script>

<button
	class="wallet-adapter-button {className}"
	style={`justify-content: ${justifyContent};`}
	{disabled}
	on:click
>
	{#if $$slots['start-icon']}
		<i class="wallet-adapter-button-start-icon">
			<slot name="start-icon" />
		</i>
	{/if}
	<slot />
	{#if $$slots['end-icon']}
		<i class="wallet-adapter-button-end-icon">
			<slot name="end-icon" />
		</i>
	{/if}
</button>
