// packages/ui/vue-ui/src/WalletConnectButton.vue
<script setup>
import { toRefs, computed } from 'vue';
import { useWallet } from '@solana/wallet-adapter-vue';
import WalletButton from './WalletButton.vue';
import WalletIcon from './WalletIcon.vue';

const emit = defineEmits(['click'])
const props = defineProps({ disabled: Boolean });
const { disabled } = toRefs(props);

const { wallet, connect, connecting, connected } = useWallet();

const handleClick = event => {
    emit('click', event);
    if (event.defaultPrevented) return;
    connect().catch(() => {});
};

const content = computed(() => {
    if (connecting.value) return 'Connecting ...';
    if (connected.value) return 'Connected';
    if (wallet.value) return 'Connect';
    return 'Connect Wallet';
});
</script>

<template>
    <wallet-button
        class="wallet-adapter-button-trigger"
        :disabled="disabled || ! wallet || connecting || connected"
        @click="handleClick"
    >
        <template #start-icon v-if="wallet">
            <wallet-icon :wallet="wallet"></wallet-icon>
        </template>
        <slot>
            {{ content }}
        </slot>
    </wallet-button>
</template>

// packages/antd/src/WalletConnectButton.tsx
import { useWallet } from '@solana/wallet-adapter-react';
import { Button, ButtonProps } from 'antd';
import React, { FC, MouseEventHandler, useCallback, useMemo } from 'react';
import { WalletIcon } from './WalletIcon';

export const WalletConnectButton: FC<ButtonProps> = ({ children, disabled, onClick, ...props }) => {
    const { wallet, connect, connecting, connected } = useWallet();

    const handleClick: MouseEventHandler<HTMLButtonElement> = useCallback(
        (event) => {
            if (onClick) onClick(event);
            // eslint-disable-next-line @typescript-eslint/no-empty-function
            if (!event.defaultPrevented) connect().catch(() => {});
        },
        [onClick, connect]
    );

    const content = useMemo(() => {
        if (children) return children;
        if (connecting) return 'Connecting ...';
        if (connected) return 'Connected';
        if (wallet) return 'Connect';
        return 'Connect Wallet';
    }, [children, connecting, connected, wallet]);

    return (
        <Button
            onClick={handleClick}
            disabled={disabled || !wallet || connecting || connected}
            icon={<WalletIcon wallet={wallet} />}
            {...props}
        >
            {content}
        </Button>
    );
};
