// packages/ui/vue-ui/src/WalletListItem.vue
<script lang="ts">
import { Wallet } from "@solana/wallet-adapter-wallets";
import { defineComponent, PropType } from "vue";
import WalletButton from "./WalletButton.vue";
import WalletIcon from "./WalletIcon.vue";

export default defineComponent({
    name: 'wallet-list-item',
    components: {
        WalletButton,
        WalletIcon,
    },
    props: {
        wallet: Object as PropType<Wallet>,
    },
    setup ({ wallet }) {
        return { wallet };
    },
});
</script>

<template>
    <li>
        <wallet-button @click="$emit('click')">
            <slot>
                {{ wallet.name }}
            </slot>
            <template #end-icon>
                <wallet-icon :wallet="wallet"></wallet-icon>
            </template>
        </wallet-button>
    </li>
</template>

// packages/react-ui/src/WalletListItem.tsx
import { Wallet } from '@solana/wallet-adapter-wallets';
import React, { FC, MouseEventHandler } from 'react';
import { Button } from './Button';
import { WalletIcon } from './WalletIcon';

interface WalletListItemProps {
    handleClick: MouseEventHandler<HTMLButtonElement>;
    wallet: Wallet;
}

export const WalletListItem: FC<WalletListItemProps> = ({ handleClick, wallet }) => {
    return (
        <li>
            <Button onClick={handleClick} endIcon={<WalletIcon wallet={wallet} />}>
                {wallet.name}
            </Button>
        </li>
    );
};
