// packages/core/react/src/ConnectionProvider.tsx
import type { ConnectionConfig } from '@solana/web3.js';
import { Connection } from '@solana/web3.js';
import React, { FC, ReactNode, useMemo } from 'react';
import { ConnectionContext } from './useConnection';

export interface ConnectionProviderProps {
    children: ReactNode;
    endpoint: string;
    config?: ConnectionConfig;
}

export const ConnectionProvider: FC<ConnectionProviderProps> = ({
    children,
    endpoint,
    config = { commitment: 'confirmed' },
}) => {
    const connection = useMemo(() => new Connection(endpoint, config), [endpoint, config]);

    return <ConnectionContext.Provider value={{ connection }}>{children}</ConnectionContext.Provider>;
};

// packages/ui/svelte-ui/src/lib/ConnectionProvider.svelte
<script lang="ts">
	import { Connection } from '@solana/web3.js';
	import type { Commitment, ConnectionConfig } from '@solana/web3.js';
	import { workSpace } from './workSpace';

	export let network: string,
		config: Commitment | ConnectionConfig | undefined = 'processed';

	const connection = new Connection(network, config);

	workSpace.set({ connection });
</script>
